{% set version = "4.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-edsurvey
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/EdSurvey_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/EdSurvey/EdSurvey_{{ version }}.tar.gz
  sha256: 7b28cb87437dcd0cb8f7235ed60393e15c0ab5145986f7656e61d4196d058d33

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-car
    - r-data.table >=1.11.4
    - r-dire >=2.1.0
    - r-formula
    - r-glm2
    - r-haven >=2.2.0
    - r-laf >=0.7
    - r-lfactors >=1.0.3
    - r-lme4
    - r-mass
    - r-matrix
    - r-naepirtparams
    - r-naepprimer
    - r-quantreg
    - r-readxl
    - r-tibble
    - r-wcorr
    - r-wemix >=4.0.0
    - r-xml2
    - r-xtable
  run:
    - r-base
    - r-car
    - r-data.table >=1.11.4
    - r-dire >=2.1.0
    - r-formula
    - r-glm2
    - r-haven >=2.2.0
    - r-laf >=0.7
    - r-lfactors >=1.0.3
    - r-lme4
    - r-mass
    - r-matrix
    - r-naepirtparams
    - r-naepprimer
    - r-quantreg
    - r-readxl
    - r-tibble
    - r-wcorr
    - r-wemix >=4.0.0
    - r-xml2
    - r-xtable

test:
  commands:
    - $R -e "library('EdSurvey')"           # [not win]
    - "\"%R%\" -e \"library('EdSurvey')\""  # [win]

about:
  home: https://www.air.org/project/nces-data-r-project-edsurvey
  dev_url: https://github.com/American-Institutes-for-Research/EdSurvey
  license: GPL-2.0-only
  summary: 'Read in and analyze functions for education survey and assessment data from the National Center for Education Statistics (NCES) <https://nces.ed.gov/>, including National Assessment of Educational Progress (NAEP) data <https://nces.ed.gov/nationsreportcard/> and data from the International Assessment Database:
    Organisation for Economic Co-operation and Development (OECD) <https://www.oecd.org/>, including Programme for International Student Assessment (PISA), Teaching and Learning International Survey (TALIS), Programme for the International Assessment of Adult Competencies (PIAAC), and International Association for the Evaluation
    of Educational Achievement (IEA) <https://www.iea.nl/>, including Trends in International Mathematics and Science Study (TIMSS), TIMSS Advanced, Progress in International Reading Literacy Study (PIRLS), International Civic and Citizenship Study (ICCS), International Computer and Information Literacy Study (ICILS), and
    Civic Education Study (CivEd).'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - khusmann
